version: "3.5"

services:
  bot_redis:
    image: redis:6-alpine
    ports:
      - '127.0.0.1:35006:6379'
    volumes:
      - redis:/var/lib/redis
    restart: always 

  bot: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4161
    depends_on:
      - bot_redis
    restart: always 

volumes:
  redis:
    driver: local

networks:
  default:
    name: exchanger_net