[bot]
token = "1955699495:AAEGFazEMR6nsfcwM3aQwiQAfHxmFOewkHw"
debug = false
tmp = "./tmp"

[api]
url = "http://127.0.0.1:4000"

[nsq]
host = "80.87.197.206"
port = 4161

[redis]
host = "localhost"
port = 6379