[bot]
token = "2126215860:AAFG2mvnRYojY17lJPsqYwz2yhyszoJOBfY"
developers = ["I0HuKc"]
debug = false
tmp = "/var/www/html/tmp"

[api]
url = "http://80.87.197.206:4000"

[nsq]
host = "80.87.197.206"
port = 4161

[redis]
host = "localhost"
port = 6379